# Generated by Django 5.0.3 on 2025-01-26 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("farmers", "0002_farmer_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="added_by",
        ),
    ]
